### PR TITLE
Allows disable HTML modifications

### PR DESCRIPTION
**Pull request by ocubom**
Use html option instead of file option to disable modification of source files

### CODE REVIEW

**Comment by haydenbleasel** [comment]
@ocubom Is there a cleaner way to write this than a Yoda Expression? E.g.

```
(null === options.html ? file.path : options.html)   ==>   (options.html || file.path)
```

Something like that? Haven't type checked so I'm not sure if `options.html ||` will work.

**Comment by ocubom** [comment]
I think it must work. I'll try that tomorrow

**Comment by ocubom** [comment]
Finally I had time to check the expression and the operator || does not work. It just do the opposite: assigns the value when we want to pass the null value.

**Comment by haydenbleasel** [comment]
Hey @ocubom, same deal as `gulp-robots`, this module is deprecated and this issue no longer applies. Please check out / star [humans-generator](https://github.com/haydenbleasel/humans-generator) if you've got the time :)

**Pull request closed without merging**
